//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Globalization;
using System.Web.Security;

namespace MMC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Nome da rua")]
        public string Rua { get; set; }

        [Required]
        [Display(Name = "Número")]
        public int Numero { get; set; }
        
        public string Bairro { get; set; }
        
        [Required]
        [Display(Name = "CEP")]
        public string CEP { get; set; }
        
        public string Cidade { get; set; }
        
        public string Estado { get; set; }
        
        public string Complemento { get; set; }

        [Required]
        [Display(Name = "Telefone de contato")]
        public string Telefone1 { get; set; }

        [Display(Name = "Telefone Celular")]
        public string Telefone2 { get; set; }
        
        public Nullable<int> Cliente_id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
