//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public int Id { get; set; }
        public double QtdHoras { get; set; }
        public System.DateTime DataLancamento { get; set; }
        public string Descrição { get; set; }
        public int Tarefa_Id { get; set; }
        public int Usuario_Id { get; set; }
    
        public virtual Tarefa Tarefa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
