//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        public Projeto()
        {
            this.Tarefas = new HashSet<Tarefa>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataInicio { get; set; }
        public Nullable<System.DateTime> DataFinal { get; set; }
        public string Descricao { get; set; }
        public int Status_Id { get; set; }
        public int Cliente_Id { get; set; }
        public System.DateTime DataHora { get; set; }
        public Nullable<decimal> Valor { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Tarefa> Tarefas { get; set; }
    }
}
