//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Projetos = new HashSet<Projeto>();
            this.Tarefas = new HashSet<Tarefa>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public bool Ativo { get; set; }
    
        public virtual ICollection<Projeto> Projetos { get; set; }
        public virtual ICollection<Tarefa> Tarefas { get; set; }
    }
}
