//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        public int Id { get; set; }
        public string Numero { get; set; }
        public int Ddd { get; set; }
        public Nullable<int> Ramal { get; set; }
        public string Contato { get; set; }
        public Nullable<int> Endereco_Id { get; set; }
    
        public virtual Endereco Endereco { get; set; }
    }
}
