//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Historicos = new HashSet<Historico>();
            this.Projetos = new HashSet<Projeto>();
            this.Skills = new HashSet<Skill>();
            this.Tarefas = new HashSet<Tarefa>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Senha { get; set; }
        public Nullable<int> Setor_Id { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public string Email { get; set; }
        public string TipoUsuario { get; set; }
        public Nullable<decimal> CustoHora { get; set; }
    
        public virtual ICollection<Historico> Historicos { get; set; }
        public virtual ICollection<Projeto> Projetos { get; set; }
        public virtual Setore Setore { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
        public virtual ICollection<Tarefa> Tarefas { get; set; }
    }
}
